#!/usr/bin/env python3
"""
Generate numbers-pcp-qualitative.tex from PredExe qualitative analysis.

Usage:
  python scripts/generate_pcp_qualitative_numbers.py
  python scripts/generate_pcp_qualitative_numbers.py --seed 42
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from analyze_pcp_qualitative import (  # noqa: E402
    DATASET_SPLITS,
    TABLE_COLUMNS,
    TOP_MODELS,
    collect_cases,
)

OUTPUT = REPO_ROOT / "papers" / "lmpl26" / "tables" / "numbers-pcp-qualitative.tex"
DEFAULT_SEED = "42"

MODEL_SLUGS = {
    "DeepSeek-Qwen 32B": "dpsk32",
    "Qwen2.5-Coder 32B-CoT": "qwen32cot",
    "Ministral 14B-CoT": "min14cot",
}

SPLIT_SLUGS = {
    "human_written": "hw",
    "fuzzer_generated": "fuzzgen",
    "synthetic_cpp": "llmtrans",
}


def latex_num(value: int) -> str:
    if value >= 1000:
        text = f"{value:,}"
        return text.replace(",", "{,}")
    return str(value)


def split_model_stats(summaries: dict) -> dict[str, dict[str, dict]]:
    stats_by_split: dict[str, dict[str, dict]] = {
        split: {} for split in DATASET_SPLITS
    }
    for split in DATASET_SPLITS:
        for model in TOP_MODELS:
            total_failures = 0
            false_success = 0
            wrong_rule = 0
            false_error = 0
            total_programs = 0
            for col in TABLE_COLUMNS:
                cell = summaries[col].get(f"{model.short_label}:{split}", {})
                total_programs += cell.get("total", 0)
                modes = cell.get("mode_counts", {})
                for mode, count in modes.items():
                    if mode == "correct":
                        continue
                    total_failures += count
                    if mode == "false_success":
                        false_success += count
                    elif mode == "wrong_rule":
                        wrong_rule += count
                    elif mode == "false_error":
                        false_error += count
            stats_by_split[split][model.short_label] = {
                "total_programs": total_programs,
                "total_failures": total_failures,
                "false_success": false_success,
                "wrong_rule": wrong_rule,
                "false_error": false_error,
            }
    return stats_by_split


def range_macro(prefix: str, values: list[int]) -> list[str]:
    return [
        f"\\DefMacro{{{prefix}-min}}{{{min(values)}}}",
        f"\\DefMacro{{{prefix}-max}}{{{max(values)}}}",
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", default=DEFAULT_SEED)
    args = parser.parse_args()

    _, summaries, _ = collect_cases(list(TABLE_COLUMNS), args.seed, top_n=2)
    split_stats = split_model_stats(summaries)

    lines = [
        "%% Automatically generated by: generate_pcp_qualitative_numbers.py",
        f"%% Seed: {args.seed}",
        "",
        "\\DefMacro{pcp-qual-seed}{" + args.seed + "}",
        "\\DefMacro{pcp-qual-failure-mode-count}{4}",
        "\\DefMacro{pcp-qual-config-count}{6}",
        "\\DefMacro{pcp-qual-top-n-failures}{2}",
        "\\DefMacro{pcp-qual-example-count}{2}",
        "\\DefMacro{pcp-qual-example-loc}{5}",
        "",
        "%% SOS rule numbers used in qualitative examples.",
        "\\DefMacro{pcp-qual-sos-rule-continue}{76}",
        "\\DefMacro{pcp-qual-sos-rule-break}{73}",
        "\\DefMacro{pcp-qual-sos-rule-modbyzero}{23}",
        "\\DefMacro{pcp-qual-sos-rule-modbyzero-neighbor}{24}",
        "\\DefMacro{pcp-qual-sos-rule-varusebdec}{2}",
        "",
    ]

    for split in DATASET_SPLITS:
        slug = SPLIT_SLUGS[split]
        model_stats = split_stats[split]
        failures = [stats["total_failures"] for stats in model_stats.values()]
        false_successes = [stats["false_success"] for stats in model_stats.values()]
        wrong_rules = [stats["wrong_rule"] for stats in model_stats.values()]
        false_errors = [stats["false_error"] for stats in model_stats.values()]
        programs = next(iter(model_stats.values()))["total_programs"]

        lines.append(f"%% {split}")
        lines.append(f"\\DefMacro{{pcp-qual-{slug}-programs-total}}{{{latex_num(programs)}}}")
        lines.extend(range_macro(f"pcp-qual-{slug}-failures", failures))
        lines.extend(range_macro(f"pcp-qual-{slug}-false-success", false_successes))
        lines.extend(range_macro(f"pcp-qual-{slug}-wrong-rule", wrong_rules))
        lines.extend(range_macro(f"pcp-qual-{slug}-false-error", false_errors))

        for model in TOP_MODELS:
            stats = model_stats[model.short_label]
            model_slug = MODEL_SLUGS[model.short_label]
            lines.append(
                f"\\DefMacro{{pcp-qual-{slug}-failures-{model_slug}}}"
                f"{{{stats['total_failures']}}}"
            )
            lines.append(
                f"\\DefMacro{{pcp-qual-{slug}-false-success-{model_slug}}}"
                f"{{{stats['false_success']}}}"
            )
            lines.append(
                f"\\DefMacro{{pcp-qual-{slug}-wrong-rule-{model_slug}}}"
                f"{{{stats['wrong_rule']}}}"
            )
            lines.append(
                f"\\DefMacro{{pcp-qual-{slug}-false-error-{model_slug}}}"
                f"{{{stats['false_error']}}}"
            )
        lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
